### ISSUE TITLE
Building on Apple silicon

### ISSUE THREAD

**Issue by yoachim** [oorb/oorb#155]
Has anyone managed to build oorb on an M1/M2 Apple chip yet? I've attempted with the conda gfortran and ended up with

> gfortran -O2 -fPIC -std=f95 -fall-intrinsics -cpp -flto -pipe -funroll-loops -fstack-arrays -fno-protect-parens oorb.o ../lib/liboorb.a -llapack -o ../main/oorb.tmp
Undefined symbols for architecture arm64:
  "_expq", referenced from:
      ___physicalparameters_cl_MOD_massestimation_mcmc in liboorb.a(PhysicalParameters_class.o)
  "_logq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in liboorb.a(random.o)
  "_powq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in liboorb.a(random.o)
  "_sqrtq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in liboorb.a(random.o)
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[1]: *** [../main/oorb] Error 1
make: *** [all] Error 2

This is with procedure
conda create -n oorb
conda activate oorb
conda install -c conda-forge  make gfortran python numpy
./configure gfortran opt --with-python
make

This gives me python 3.10.9, gfortran 11.3.0

**Comment by rhiannonlynne** [comment]
As another confirmation -- on a different machine, with gfortran installed from conda, same error. 

`gfortran -O2 -fPIC -std=f95 -fall-intrinsics -cpp -flto -pipe -funroll-loops -fstack-arrays -fno-protect-parens -shared parameters.o utilities.o random.o sort.o statistics.o functions.o linal.o estimators.o planetary_data.o cl_options.o integrators.o data_structures.o Base_class.o Unit_class.o File_class.o Time_class.o Observatory_class.o SphericalCoordinates_class.o CartesianCoordinates_class.o Observation_class.o Observatories_class.o Orbit_class.o Observations_class.o StochasticOrbit_class.o PhysicalParameters_class.o io.o -llapack -o ../lib/liboorb.dylib
Undefined symbols for architecture arm64:
  "_expq", referenced from:
      ___physicalparameters_cl_MOD_massestimation_mcmc in PhysicalParameters_class.o
  "_logq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in random.o
  "_powq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in random.o
  "_sqrtq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in random.o
ld: symbol(s) not found for architecture arm64` 


With gfortran installed from homebrew: there are version warnings (because the system is os 11 and some things appear to be targeted for os 10.12 somewhere?) but everything does build. Homebrew provides gfortran although it's 12.2.0 and maybe has some extras. 

```(oorb-dev) prat@m1pro oorb % gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/opt/homebrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/aarch64-apple-darwin21/12/lto-wrapper
Target: aarch64-apple-darwin21
Configured with: ../configure --prefix=/opt/homebrew/opt/gcc --libdir=/opt/homebrew/opt/gcc/lib/gcc/current --disable-nls --enable-checking=release --with-gcc-major-version-only --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-12 --with-gmp=/opt/homebrew/opt/gmp --with-mpfr=/opt/homebrew/opt/mpfr --with-mpc=/opt/homebrew/opt/libmpc --with-isl=/opt/homebrew/opt/isl --with-zstd=/opt/homebrew/opt/zstd --with-pkgversion='Homebrew GCC 12.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --with-system-zlib --build=aarch64-apple-darwin21 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Homebrew GCC 12.2.0)```

**Comment by rhiannonlynne** [comment]
This is apparently the same error as the REAL*16, although it sounds fairly different. 
https://github.com/oorb/oorb/issues/146

**Comment by mgranvik** [comment]
PR #162 should have solved this issue. Let me know if it works.
