### ISSUE TITLE
oorb struggles with new MPCORB files

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#159]
We at Karman+ noticed that oorb has problems dealing with recent MPCORB files.
I suspect (but do not know for sure) that the issue is that oorb has not been updated to account for packed designations past the number 619,999, which the MPC did an update on their end for - see this MPML discussion: https://groups.io/g/mpml/topic/95396761

As an example to demonstrate the problem, see the following terminal output:
```
$ ./oorb --task=ephemeris --orb-in= mpcorb_new.orb
***ERROR*** 30 Mar 2023 13:33:52UTC (oorb) Could not sort orbit id's.  -> sort : quickSort : NSTACK too small.
```
where mpcorb_new.orb has been created with the mpcorb task with MPCORB.DAT downloaded from today.

With an older MPCORB I had locally this does not occur.

**Comment by Siltala** [comment]
Actually it probably is a simpler thing - maybe simply increasing the NSTACK parameter in sort.f90 will solve this?

**Comment by mgranvik** [comment]
I doubt it has anything to do with the packed designations, because they're character strings so adding a tilde shouldn't be a problem. 

The likely reason is the NSTACK parameter being too small. It currently has a default value that has never been changed, so go ahead and increase it and see what happens.
