### ISSUE TITLE
Error in position of the Earth

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#16]
Hi Mikael, 

Investigating the discrepancies in ephemeris positions between Oorb and JPL tools, (they were very small, but noticeable -- on the order of 30km for a PHA), we found what we think is the source of the error. 

The JPL and Horizons tools predict the position of the Earth at 2008-01-01 to be 

2454466.500000000 = A.D. 2008-Jan-01 00:00:00.0000 (TDB)
  -1.676694534881328E-01  9.688884736502622E-01 -1.524731751740284E-05

but Oorb is predicting the position of the Earth at this time as:
ewok:~/otherRepos/testMOPS/mops] lynnej% oorb --task=ephemeris --orb-in=tjpl.des --obsCode=500 | awk '{print $3, $5, $6, $4, $29, $30, $31, $32, $33, $34, $35, $36, $37}'
MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
54465.9992455556 8.6672841635 7.0117874800 2.0383957293 1.8323770423 1.3475922742 0.1070109968 -0.0052274745 0.0057681062 0.0000143002 -0.1676694568 0.9688884731 -0.0000150849
(-0.1676694568 0.9688884731 -0.0000150849 for the Earth x/y/z in the same coordinates). 

So the x/y/z differences are 
array([ -0.49545533,  -0.08231922,  24.2976606 ])  kilometers
(the x difference is likely due to the difference between de431 and de405, but the z coordinate difference exists using de405 in the JPL tools, that @stevechesley has access to  .... de431-de405 has a difference of 0.49, 0.09, 1.0 km in ecliptic coordinate frame at this time). 

This is on the same order of magnitude as the errors in the positions that we see. 
Is it possible there's a bug in the de405 routines? 

*******************************************************************************
Revised: Jul 31, 2013                  Earth                                399
 
PHYSICAL PROPERTIES (revised Sep 18, 2013):
 Mean radius, km          = 6371.01+-0.01   Mass, 10^24 kg = 5.97219+-0.0006
 Equ. radius, km          = 6378.14+-0.01   Mass layers:
 Polar axis, km           = 6356.752          Atmos          = 5.1   x 10^18 kg
 Flattening               = 1/298.257         oceans         = 1.4   x 10^21 kg
 Density, gm cm^-3        = 5.515             crust          = 2.6   x 10^22 kg
 J2  (GEM T2, 1990)       = 0.0010826265      mantle         = 4.043 x 10^24 kg
 gp, m s^-2 (polar)       = 9.8321863685      outer core     = 1.835 x 10^24 kg
 ge, m s^-2 (equatorial)  = 9.7803267715      inner core     = 9.675 x 10^22 kg
 go, m s^-2               = 9.82022         Fluid core rad   = 3480 km
 GM, km^3 s^-2            = 398600.440      Inner core rad   = 1215 km
 Mean rot. rate, rad s^-1 = 7.292115*10^-5  Surface Area:
 Sidereal period, hr      = 23.93419          land           = 1.48 x 10^8 km
 Mean solar day, days     = 1.002738          sea            = 3.62 x 10^8 km
 Moment of inertia        = 0.3308          Love no., k2     = 0.299
 Mean Temperature, K      = 270             Atm. pressure    = 1.0 bar
 Solar constant, W/m^2    = 1367.6          Vis. mag. V(1,0) = -3.86
 Volume, 10^10 km^3       = 108.321         Geometric albedo = 0.367 

DYNAMICAL CHARACTERISTICS:
 Obliquity to orbit, deg  = 23.45           Sidereal period  = 1.0000174  yrs
 Orbit velocity, km s^-1  = 29.7859         Sidereal period  = 365.25636  days
 Mean daily motion, n     = 0.9856474 deg/d Escape velocity  = 11.186 km s^-1
 Hill's sphere radius     = 234.9           Magnetic moment  = 0.61 gauss Rp^3
*******************************************************************************
 
 
*******************************************************************************
Ephemeris / WWW_USER Wed Oct 28 12:03:30 2015 Pasadena, USA      / Horizons    
*******************************************************************************
Target body name: Earth (399)                     {source: DE-0431LE-0431}
Center body name: Sun (10)                        {source: DE-0431LE-0431}
Center-site name: BODY CENTER
*******************************************************************************
Start time      : A.D. 2008-Jan-01 00:00:00.0000 CT 
Stop  time      : A.D. 2008-Jan-02 00:00:00.0000 CT 
Step-size       : 14400 minutes
*******************************************************************************
Center geodetic : 0.00000000,0.00000000,0.0000000 {E-lon(deg),Lat(deg),Alt(km)}
Center cylindric: 0.00000000,0.00000000,0.0000000 {E-lon(deg),Dxy(km),Dz(km)}
Center radii    : 696000.0 x 696000.0 x 696000.0 k{Equator, meridian, pole}    
Output units    : AU-D                                                         
Output format   : 03
Reference frame : ICRF/J2000.0                                                 
Output type     : GEOMETRIC cartesian states
Coordinate systm: Ecliptic and Mean Equinox of Reference Epoch                 
*******************************************************************************
JDCT 
   X     Y     Z
   VX    VY    VZ
   LT    RG    RR
*******************************************************************************
$$SOE
2454466.500000000 = A.D. 2008-Jan-01 00:00:00.0000 (TDB)
  -1.676694534881328E-01  9.688884736502622E-01 -1.524731751740284E-05
  -1.723508181797047E-02 -2.992178149567813E-03  5.120885090408132E-07
   5.679005590891073E-03  9.832893369897919E-01 -9.448062173113097E-06
$$EOE
*******************************************************************************
Coordinate system description:

  Ecliptic and Mean Equinox of Reference Epoch

    Reference epoch: J2000.0
    xy-plane: plane of the Earth's orbit at the reference epoch
    x-axis  : out along ascending node of instantaneous plane of the Earth's
              orbit and the Earth's mean equator at the reference epoch
    z-axis  : perpendicular to the xy-plane in the directional (+ or -) sense
              of Earth's north pole at the reference epoch.

Symbol meaning [1 au=149597870.700 km, 1 day=86400.0 s]:

    JDTDB    Epoch Julian Date, Barycentric Dynamical Time
      X      x-component of position vector (AU)                               
      Y      y-component of position vector (AU)                               
      Z      z-component of position vector (AU)                               
      VX     x-component of velocity vector (AU/day)                           
      VY     y-component of velocity vector (AU/day)                           
      VZ     z-component of velocity vector (AU/day)                           
      LT     One-way down-leg Newtonian light-time (day)                       
      RG     Range; distance from coordinate center (AU)                       
      RR     Range-rate; radial velocity wrt coord. center (AU/day)            

Geometric states/elements have no aberration corrections applied.

 Computations by ...
     Solar System Dynamics Group, Horizons On-Line Ephemeris System
     4800 Oak Grove Drive, Jet Propulsion Laboratory
     Pasadena, CA  91109   USA
     Information: http://ssd.jpl.nasa.gov/
     Connect    : telnet://ssd.jpl.nasa.gov:6775  (via browser)
                  telnet ssd.jpl.nasa.gov 6775    (via command-line)
     Author     : Jon.Giorgini@jpl.nasa.gov
*******************************************************************************

**Comment by rhiannonlynne** [comment]
The test program - ephtester - seems like it may be failing also (although it doesn't give an error message).  (I can email you the file, but apparently not allowed to upload it here). The 'difference' column has occasional values which are larger than 1.

**Comment by mgranvik** [comment]
On Oct 28, 2015 at 21:13, Lynne Jones wrote:

> 
> So the x/y/z differences are
> array([ -0.49545533, -0.08231922, 24.2976606 ]) kilometers
> (the x difference is likely due to the difference between de431 and de405, but the z coordinate
> difference exists using de405 in the JPL tools, that @stevechesley has access to .... de431-de405 has
> a difference of 0.49, 0.09, 1.0 km in ecliptic coordinate frame at this time).
> 
> This is on the same order of magnitude as the errors in the positions that we see.
> Is it possible there's a bug in the de405 routines?

I have started digging into this and it seems that the de405 routines are okay, 
because the error goes away when comparing equatorial coordinates: the 
differences between Horizon and OpenOrb are (in km)

  0.490313 -0.319815 0.954146

So as unbelievable as it may sound the problem could be in the conversion from 
the equatorial frame to the ecliptic frame. I'll continue to investigate this 
issue.

Note that ephtester results show large errors when the target is 13 (the 
Earth-Moon barycenter). The coordinates of the Earth-Moon barycenter are hardly 
ever used in orbit computation and I have therefore not bothered looking into 
why the code produces wrong results. All the other coordinates are reproduced 
with a precision better than 0.0000000000001 au so well within the uncertainty 
of the de405 ephemerides.

Mikael

**Comment by rhiannonlynne** [comment]
Thanks Mikael. Coincidentally, we were wondering what target=13 was.

**Comment by stevechesley** [comment]
And just to clarify for Lynne, Mikael's difference [0.490313 -0.319815 0.954146] is in Equatorial frame, and rotating to ecliptic that matches what I said: [0.49, 0.09, 1.00] km.

-Steve

On Oct 29, 2015, at 11:44 AM, Mikael Granvik <notifications@github.com<mailto:notifications@github.com>> wrote:



On Oct 28, 2015 at 21:13, Lynne Jones wrote:

>
> So the x/y/z differences are
> array([ -0.49545533, -0.08231922, 24.2976606 ]) kilometers
> (the x difference is likely due to the difference between de431 and de405, but the z coordinate
> difference exists using de405 in the JPL tools, that @stevechesley has access to .... de431-de405 has
> a difference of 0.49, 0.09, 1.0 km in ecliptic coordinate frame at this time).
>
> This is on the same order of magnitude as the errors in the positions that we see.
> Is it possible there's a bug in the de405 routines?

I have started digging into this and it seems that the de405 routines are okay,
because the error goes away when comparing equatorial coordinates: the
differences between Horizon and OpenOrb are (in km)

0.490313 -0.319815 0.954146

So as unbelievable as it may sound the problem could be in the conversion from
the equatorial frame to the ecliptic frame. I'll continue to investigate this
issue.

Note that ephtester results show large errors when the target is 13 (the
Earth-Moon barycenter). The coordinates of the Earth-Moon barycenter are hardly
ever used in orbit computation and I have therefore not bothered looking into
why the code produces wrong results. All the other coordinates are reproduced
with a precision better than 0.0000000000001 au so well within the uncertainty
of the de405 ephemerides.

Mikael

**Comment by mgranvik** [comment]
Okay, I found the problem: the J2000.0 obliquity (of the ecliptic) used by 
OpenOrb and Horizons seems to differ slightly. You can fix this by going to 
classes/Base_class.f90 and commenting out this:

REAL(bp), PARAMETER :: eps      = 23.439281111_bp*rad_deg !! Obliquity of ecliptic (J2000.0) JPL 2005.

and uncommenting this:

!REAL(bp), PARAMETER :: eps      = 23.43929111111_bp*rad_deg !! Obliquity of ecliptic (J2000.0), old code

Then do a 'make all_clean' and, in main/, 'make oorb'. With the new obliquity 
you will get differences that are exactly equal to those computed by 
@stevechesley :

   [0.49 0.09 1.00] km

@stevechesley may also want to comment on the fact that I needed to change to an 
old J2000.0 obliquity from 1984 (see, e.g., 
https://en.wikipedia.org/wiki/Ecliptic#Obliquity_of_the_ecliptic) to reproduce 
the Horizons result. Is it, perhaps, a question of internal consistency?

The 2010 estimate for the J2000.0 obliquity is 23.439279444 deg.

Mikael

**Comment by stevechesley** [comment]
Ah, that explains all. Thanks for figuring this out, Mikael. It looked like a bug because it was only in Z, but a different obliquity would indeed put you off in Z and still okay in X & Y�

So here's the deal: JPL continues to use the 1976 IAU constants, as does the MPC and OrbFit. The point here is that the governing planetary ephemerides are in the equatorial frame, and so are RA-DEC. In our code we convert ecliptic elements to equatorial states and integrate with the already equatorial frame perturbers. Then there is no rotation needed to compute RA-DEC, and no rotation of the planetary ephemerides. I would guess that oorb operates the same way.

But we do (usually) distribute elements in ecliptic frame. Here our view is that consistency is more important than accuracy. And so from this perspective, even as the J2000 obliquity has been refined (by only 30-40 mas) in subsequent decades, there is no material benefit to changing this constant. Otherwise everybody could be using a different value at different times and comparisons become quite complicated. And if you have ecliptic elements that are based on one value of epsilon and later try to use them after you "updated" your value of epsilon then you have a mess. This would be true even internally with the same code base: You would need to adjust all of the Euler angles in your asteroid catalog every time you tweak the obliquity of the ecliptic.

So the true reference frame is the (equatorial) frame of the planetary ephemeris, and this can change with the passing years. But our ecliptic coordinates are forever defined by the IAU76 obliquity. I don't think that this approach is an official IAU standard, but the alternative is too messy.

For the IAU76 constants, see  <https://en.wikipedia.org/wiki/IAU_(1976)_System_of_Astronomical_Constants>.

Anyway, Lynne, you should make the code mods suggested by Mikael and then continue with the tests. I think that we will at least get agreement on the 2008 RA-DEC. Let's see what happens with the 1996 case.

-Steve

**Comment by mgranvik** [comment]
Thanks for the explanation, Steve. I was unaware of the common choice to stay 
with the 1976 IAU constants. I will change the default obliquity in OpenOrb to 
follow this convention.

Mikael
