### ISSUE TITLE
MCMC mass estimation broken

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#161]
I was trying out the mass estimation code with the latest master and it is now completely unusable - it does not crash, but it is insanely slow for reasons I haven't yet figured out.

This is caused by commit https://github.com/oorb/oorb/commit/9250ab2359df9268f3aacd44d3d94214fba8acd7  - before that commit everything works perfectly fine.

I'll try to figure this one out myself

**Comment by mgranvik** [comment]
@Siltala: note that you may have to rerun the lsl solutions because the orbit format has been updated, too. Also, I suggest you check out the pseudo-covariance matrices that are used for the generation of proposals, because the upper off-diagonal elements are now set to zero *within* cholesky_decomposition but perhaps there is confusion as to which part (upper or lower) is zeroed.

**Comment by Siltala** [comment]
Good shout about rerunning the lsl solutions; actually just computing new orbits fixed the problems already. So everything seems fine. Thanks!
