### ISSUE TITLE
apparent magnitude predictions

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#70]
To get the issue on record (especially for reproducibility purposes):

In recent updates to the python interface to oorb, the apparent magnitude calculation has been changed from its previous behavior so that now, if the orbit format is "COM" then the apparent magnitude will be calculated based on distance only (no phase function component), while for other orbital element formats, the apparent magnitude will be calculated including the H/G phase function. 

Because this was behavior that was unwanted for most LSST applications, in the lsst fork of oorb, I have reverted this behavior to the original (always using H/G instead). (see e.g. https://github.com/lsst/oorb/blob/lsst-dev/python/pyoorb.f90#L699 vs. https://github.com/oorb/oorb/blob/master/python/pyoorb.f90#L700).  A primary function of this issue is to raise awareness of this difference, and to speed re-integration to a single version.

Instead of having the magnitude calculation depend on the orbital element format, it would be better to have which calculation is used depend on a flag or configuration set by the user (or, minimally .. set by the value of the G parameter in the orbit = if G is None, then no phase function, if G is present, use H/G .. could also extend to using H/G12 or H/G1/G2).

**Comment by mgranvik** [comment]
I completely agree with Lynne. The change slipped through the cracks when I 
approved the change to the Python code. Apologies for that.

Note that the Fortran version of OpenOrb (main/oorb.f90) uses a flag 
("--cometary-magnitude") to force calculation of cometary apparent magnitudes in 
the obsplanner task. (The option of using cometary magnitudes hasn't been 
implemented for the other tasks.)

I would prefer having an explicit flag for cometary magnitudes because the 
common assumption is G=0.15 if G isn't explicitly provided.

Mikael

**Comment by rhiannonlynne** [comment]
This has been reverted to the 'original' behavior as of PR #72.
