### ISSUE TITLE
Proposal for a new versioning scheme

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#78]
Hi all,

With the new versioning and unit test stuff in PR #73 I feel now is a good time to consider implementing a clearer version scheme.

To this end, I suggest that we switch to a date-based versioning scheme such as, say, the one Ubuntu uses, i.e. using version numbers of the form "year.month" so that, e.g. a hypothetical oorb release this month would be versioned 19.02.
I, at least, find it a clear scheme and simple enough for our purposes.
I also suggest starting to make official releases annually on say, every January (or biannually?) which we can hopefully test with the upcoming unit tests before pushing a release to Github complete with release notes. 
Of course, should the need arise, one could make 'interim' releases in addition to the annual ones.

Do let me know what you think!

**Comment by mjuric** [comment]
Thanks for starting this up!!

The nice thing about [SemVer](https://semver.org/)-style versions is that the version conveys a meaning to the end-user and other development beyond just a release date. With `major`.`minor`.`patchlevel` scheme one can easily determine what to expect from a given release of the code  (`major` changes when some API or command line option is changed in an incompatible way, `minor` changes when non-breaking changes are added, while `pachlevel` indicates a bugfix with no new features).

This has advantages when the code is used by downstream projects and users:
  * It makes it easy for us to know when it's safe to upgrade w/o our scripts breaking.
  * It makes it possible to write code that tests whether one has (say) a 1.x version installed and refuse to work otherwise (or use different code paths for version 1.x vs 2.x -- like we sometimes do to support Py2 and Py3). If the releases are date-based, there's no way for a code that uses openorb as a library to know that some future oorb release has changed in an incompatible way (best case, it crashes -- a much more worrying case, it silently gives the wrong result).
  * SemVer works with out-of-the-box with packaging systems (deb, conda, etc.), where one can write relationships such as "works with oorb version >= 1.23 and <=2". Package management is more robust.

It would be possible to make things work with dates, but then we'd effectively have to find another way to convey this information about compatibility (which I fear may generate more work than maintaining the x.y.z. versions).

**Comment by Siltala** [comment]
> It makes it easy for us to know when it's safe to upgrade w/o our scripts breaking.
Regarding this point, I think/hope that proper testing before releasing should mitigate this (though I suppose it won't guarantee that everything will keep working, especially with scripts not part of oorb itself). Your PR and the tests+CI it promises was actually what inspired me to see if we can get proper versioning/releases happening 

Your comments do make sense and I agree that this approach does have its drawbacks.
In turn, the main benefits I was thinking of are:
-It's trivial for end users to see how old their current version is
-Also makes it trivial for openorb to have a regular release schedule
-Also trivial for developers to understand (and figure out how to number a new release)

In theory one could also do a 'hybrid' approach, e.g. 1.year.month (so, for instance, 1.19.02) where the latter two number represent year and month of release and the first number could be bumped up when we expect a new version to have major incompatibilities with the previous one. I'm not (yet) sure whether I like that idea though. In any case, I don't actually see 2.x release for openorb ever happening but you never know..

In any case, currently the latest version number is 1.0.1 - this is from 8 years ago! so I'm sure we can agree that, in some form, we really could use more regular releases.

**Comment by mjuric** [comment]
> > It makes it easy for us to know when it's safe to upgrade w/o our scripts breaking.
>
> Regarding this point, I think/hope that proper testing before releasing should mitigate this (though I suppose it won't guarantee that everything will keep working, especially with scripts not part of oorb itself). Your PR and the tests+CI it promises was actually what inspired me to see if we can get proper versioning/releases happening

Definitely agree -- for oorb itself the internal self-consistency is ensured by the test suite; it's for the downstream users where it matters more (few of us are conscientious enough to keep a test suite for our research of the day 😀).

How about this as a solution: construct versions as, say,:
```
x.y.z+YYYYMMDD
```
This still has the compatibility semantics, but encodes the release date as well. It's also allowed by the SemVer spec -- anything past the `+` sign is considered [informational build metadata](https://semver.org/#spec-item-10) -- so packaging systems will know how to handle it. Microsoft does something similar to encode dates into build numbers.

PS: One could even have cute Ubuntu-style code-names, e.g.:
```
1.2.5+20190601.AsteroidalAnteater
...
1.2.5+20260601.OrbitalOtter
```
(though I suspect for the next year the releases may be much more frequent than semi-annual, with all the good stuff that @mommermi et al. are adding to pyoorb!).

**Comment by rhiannonlynne** [comment]
Let me add another vote in favor of SemVer versioning! 
For one thing: I do note that different versions of openorb require different fortran compilers. This is a breaking change for some environments, and I would suspect means changing the 'major' version. 
You may eventually have different command line options or output formats - these would also be major version changes. 

A minor version change would be something like an update to how a particular orbit fitting routine works, if it doesn't substantially change the results but maybe makes things more robust.
A major version change might be if the ecliptic angle interpretation is changed (this probably isn't going to happen again, but something like it did happen at one point).

**Comment by oorb** [comment]
We've decided to go forward with basic SemVer (MAJOR. MINOR.PATCH). MAJOR will likely not change anytime soon whereas MINOR will change semiregularly every 3-6 months if the code has changed significantly.
